ensemble_model:
  ensemble_config:
    models:
      - random_forest
      - xgboost
      - neural_network
    voting: soft
  hyperparameters:
    n_estimators: 100
    random_state: 42
  model_type: ensemble
hybrid_model:
  hyperparameters:
    dropout_rate: 0.2
    fusion_strategy: attention
  model_type: multimodal
stacking_ensemble:
  model_type: ensemble
  hyperparameters:
    n_folds: 5
    use_proba: true
  ensemble_config:
    base_models:
      - random_forest
      - gradient_boosting
      - logistic_regression
    meta_model: logistic_regression
  explainability_config: {}
